language: node_js
node_js: node
cache:
  directories:
  - node_modules
script:
  - npm test
env:
  - CI=true
deploy:
  provider: heroku
  app: neighborFoods-react-front-end
  on:
    repo: roshnikutty/neighborFoods-react-front-end
